
package speedsocket;


public enum Posicion {
	//ARQUERO, DEFENSA, MEDIOCAMPISTA, DELANTERO, VOLANTES, CENTRALES
	POINT_ARQUERO, POINT_DEFENSA, POINT_MEDIOCAMPISTA, POINT_DELANTERO, POINT_VOLANTES, POINT_CENTRALES   
}
